FROM node:18-alpine AS BUILD
WORKDIR /app
COPY package*.json ./
RUN npm install --production

COPY . .
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
