FROM golang:1.25.4-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /api-server ./cmd/main.go

FROM gcr.io/distroless/base-debian11
WORKDIR /
COPY --from=build /api-server /api-server

EXPOSE 8080
USER nonroot:nonroot

ENTRYPOINT [ "/api-server" ]
